### ISSUE TITLE
IncrementalImmutableSequentialGraph got blocked

### ISSUE THREAD

**Issue by xindubawukong** [vigna/webgraph#11]
In https://github.com/vigna/webgraph/blob/master/src/it/unimi/dsi/webgraph/IncrementalImmutableSequentialGraph.java, the `successorQueue ` has a default size 100.

So if we call `add` for more than 100 times, this queue will be blocked and nothing can proceed.

**Comment by vigna** [comment]
It's implemented using a producer/consumer paradigm. If the queue is blocked is because nobody is storing the graph. There must be a parallel thread emptying the queue by scanning the graph.

If you need a mutable graph please use `ArrayListMutableGraph`.
