### ISSUE TITLE
Can't not find or load main class

### ISSUE THREAD

**Issue by PeterDykas** [vigna/webgraph#3]
Hi,

I have been able to build the project with the ant command given `ant ivy-setupjars jar` which gives me a BUILD SUCCESSFUL.  However when I run the command `java it.unimi.dsi.webgraph.BVGraph.java -o -O -L` it tells me 

```
Error: Could not find or load main class it.unimi.dsi.webgraph.BVGraph.java
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.webgraph.BVGraph.java
```
I am in Ubuntu 18.04.
Is there something more I should be doing then the ant setup to get this to work?

**Comment by vigna** [comment]
You are clearly not setting the CLASSPATH. Please do.

**Comment by YuxinxinChen** [comment]
This totally doesn't make sense. If I need to add CLASSPATH myself, then how it gonna to look like(https://stackoverflow.com/questions/21918454/trying-to-install-webgraph-to-run-a-class)?:
```
java -classpath collections-generic-4.01.jar;colt-1.2.0.jar;commons-collections-20040616.jar;commons-configuration-1.8.jar;commons-io-2.4.jar;commons-lang-2.6.jar;commons-math3-3.2.jar;concurrent-1.3.4.jar;dsiutils-2.1.8.jar;fastutil-6.5.12.jar;guava-16.0.1.jar;jsap-2.1.jar;jung-algorithms-2.0.1.jar;jung-api-2.0.1.jar;jung-io-2.0.1.jar;log4j-over-slf4j-1.7.6.jar;logback-classic-1.1.1.jar;logback-core-1.1.1.jar;slf4j-api-1.7.6.jar;stax-api-1.0.1.jar;sux4j-3.0.10.jar;webgraph-3.3.1.jar it.unimi.dsi.webgraph.BVGraph
```
Essentially, the library requires so many unmentioned dependencies and requires the users to spend time figuring it out!

And somehow the only way to use webgraph is use maven which I will never use it.  Not use me and @PeterDykas has this dependency issue, this guy also had https://stackoverflow.com/questions/37415487/specifying-main-class-via-java-cp-jar-package-path-classname-wont-work.

Anyway, I am so tried trying to use webgraph, it is so hard to use, and the owner expects the user to figure out too many details.
