### ISSUE TITLE
what's the content(format) in .properties file?

### ISSUE THREAD

**Issue by houn27** [vigna/webgraph#6]
Hi @vigna , 
thanks for your contribution to this open-source project 

I try to load a .txt graph dataset in ASC2 format by the function `ImmutableGraph.load(basename, pl);` from local disk. When I run it, there is an error of `The property file for {basename} does not contain a graphclass property`. when I refer to the source code of "load()" function, the extension of "basename" file is automatically added with ".properties" as a java configuration file.

![image](https://user-images.githubusercontent.com/21981155/159246349-c90361b9-5024-4aa4-83ff-a7fc5d1bead0.png)

what should I write in the ".properties" file and how to contain graphclass properties? thanks

**Comment by vigna** [comment]
> On 21 Mar 2022, at 11:48, Ron ***@***.***> wrote:
> 
> 
> Hi @vigna ,
> thanks for your contribution to this open-source project
> 
> I try to load a .txt graph dataset in ASC2 format

I don't know this format.

> by the function ImmutableGraph.load(basename, pl);

You can't. Did you read the documentation?

Ciao,

					seba

**Comment by BearBiscuit05** [comment]
> Hi @vigna , thanks for your contribution to this open-source project
> 
> I try to load a .txt graph dataset in ASC2 format by the function `ImmutableGraph.load(basename, pl);` from local disk. When I run it, there is an error of `The property file for {basename} does not contain a graphclass property`. when I refer to the source code of "load()" function, the extension of "basename" file is automatically added with ".properties" as a java configuration file.
> 
> ![image](https://user-images.githubusercontent.com/21981155/159246349-c90361b9-5024-4aa4-83ff-a7fc5d1bead0.png)
> 
> what should I write in the ".properties" file and how to contain graphclass properties? thanks

Hi, I meet the same problem, do you know how to build the raw dataset?
